---
vector_config_dir: "/etc/vector"
data_dir: "/var/lib/vector"
sources:
  our_log:
    type: file
    include:
      - "/home/ssco/logs/*.log"
    ignore_older: 600
    read_from: beginning
sinks:
  to_clickhouse:
    inputs:
      - our_log
    type: clickhouse
    database: logs
    table: my_table
    endpoints: "http://158.160.24.80:8123"
    healthcheck: false
    compression: gzip
    skip_unknown_fields: true